### PR TITLE
Leader can now update video ID, required restructuring

### PR DESCRIPTION
**Pull request by Antrikshy**
I've been working on this on/off ever since I emailed @filahf asking if this was open for the taking. I think I've got it working pretty well, but please clone and verify that it all *actually* works.

I'll attempt to summarize all the changes within, hopefully not forgetting anything:

1. Separated YouTube URL handling functions into a linkHandler.js so I could reuse that code in both CreateSession and Video.
2. Made `useEffect` in CreateSession and Video to not fire on each render, as I noticed a significant number of extra messages being sent to the server, and I think interfered with my changes. This was my first time working with React Hooks and I don't like it. I feel some of these components are substantial enough to be class components, but it wasn't *really* worth changing right now. Crossing fingers this didn't break anything.
3. Got rid of the `action` state in App. I felt it didn't fit in well into the new paradigm with video updates, and because in my opinion, it didn't feel like a good "state" to track, as it's only used occasionally. In my opinion, the server doesn't need this same value tracked in sessions either; it feels very confusing. But I didn't want to change the latter at this time. @filahf, feel free to disagree with me here! :)
4. Added the new feature. The leader sees a new input box to update the video for everyone. I restricted this to the leader because it felt appropriate, but can be expanded easily, I think. The new message to the server is fired when this new form is  submitted. After a lot of consideration and moving code around, I figured the broadcast was best handled in Video along with other video events, as it was the easiest to update the video ID in the YouTube player in that component. This way, all users, including the leader, get their video updated at the same time.

I feel the whole app is slightly finnicky, and sessions seem to drop very frequently in my day-to-day use. I didn't come across an obvious root cause, so that still happens. I also came across an error where the `player` variable in Video is unassigned for the leader in some circumstances and the app throws errors when someone else in the session syncs their video state. But I don't have it 100% isolated and couldn't fix. I hope that doesn't interfere with the new feature in your testing!

I made some assumptions, both about the UX and naming practices (variable and function names, web socket events), that I thought made sense given your existing code. @filahf, please feel free to take over from here and restructure or rename things as you see fit!

### CODE REVIEW

**Comment by filahf** [comment]
Thank you so much for contributing! I'll as soon as possible test and go through with the merge. I haven't experienced the session drop on my end but I'll investigate that as well.

Updating the video ID during an established session has been one of the most requested features since I published site, so once again thank you for taking your time to contribute to this project.

**Comment by Antrikshy** [comment]
Bump! Would be great to have this merged in when you get a chance.

**Comment by filahf** [comment]
I am sorry that it took so long. But thank you so much for your contribution, I read every single line of code you wrote and I really like how clean looking it is! Thanks again

**Comment by Antrikshy** [comment]
Yay, exciting!

On Oct 19, 2020, at 12:22 PM, Filip Åhfelt <notifications@github.com> wrote:

﻿
I am sorry that it took so long. But thank you so much for your contribution, I read every single line of code you wrote and I really like how clean looking it is! Thanks again

**Comment by Antrikshy** [comment]
Yay, exciting! 

And no worries, I am often super lazy around my GitHub projects as well.

**Pull request merged**
